version: "3"
services:
    admin:
        build: ./admin
    api:
        build: ./rest
    unity:
        build: ./unity
    db:
        image: mongo
        volumes:
            - ../edanaga-mongodb:/data/db

