version: "3"

services:
    admin:
        build:
            context: ./admin
            dockerfile: dev.Dockerfile
        volumes:
            - "./admin/app:/opt/source-code"
        environment:
            - MONGODB=${MONGODB}
            - MONGOUSER=${MONGOUSER}
            - MONGOPASS=${MONGOPASS}
            - MONGOHOST=${MONGOHOST}
            - SECRET_KEY=${ADMIN_SECRET_KEY}
            - SECURITY_PASSWORD_SALT=${ADMIN_SECURITY_SALT}
        ports:
            - "5000:5000"
        depends_on:
            - db
    api:
        build:
            context: ./rest
            dockerfile: dev.Dockerfile
        volumes:
            - "./rest/app:/opt/source-code"
            - "./admin/app/crud/models.py:/opt/source-code/models.py"
        environment:
            - MONGODB=${MONGODB}
            - MONGOUSER=${MONGOUSER}
            - MONGOPASS=${MONGOPASS}
            - MONGOHOST=${MONGOHOST}
        ports:
            - "5001:5000"
        depends_on:
            - db
    unity:
        build:
            context: ./unity
            dockerfile: Dockerfile
        volumes:
            - "./unity/app:/opt/source-code"
        ports:
            - "5002:5000"
    db:
        image: mongo:3.4.2
        # restart: always
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGOUSER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
        ports:
            - "27017:27017"
