version: "3"

services:
    admin:
        build:
            context: ./admin
            dockerfile: dev.Dockerfile
        volumes:
            - "./admin/app:/opt/source-code"
        environment:
            - MONGODB=${MONGODB}
            - MONGOUSER=${MONGOUSER}
            - MONGOPASS=${MONGOPASS}
            - MONGOHOST=${MONGOHOST}
            - SECRET_KEY=${ADMIN_SECRET_KEY}
            - SECURITY_PASSWORD_SALT=${ADMIN_SECURITY_SALT}
            - ADMINUSER=${ADMINUSER}
            - ADMINPASS=${ADMINPASS}
        depends_on:
            - db
    api:
        build:
            context: ./rest
            dockerfile: dev.Dockerfile
        volumes:
            - "./rest/app:/opt/source-code"
            - "./admin/app/crud/models.py:/opt/source-code/models.py"
        environment:
            - MONGODB=${MONGODB}
            - MONGOUSER=${MONGOUSER}
            - MONGOPASS=${MONGOPASS}
            - MONGOHOST=${MONGOHOST}
        # /!\ WARNING: this port forwarding is meant for development use ONLY
        # Unity engine cannot resolve api.localhost, but it resolves localhost:5001
        ports:
           - "5001:5000"
        depends_on:
            - db
    unity:
        build:
            context: ./unity
            dockerfile: dev.Dockerfile
        volumes:
            - "./unity/app:/opt/source-code"
            - "./admin/app/crud/models.py:/opt/source-code/models.py"
        environment:
            - MONGODB=${MONGODB}
            - MONGOUSER=${MONGOUSER}
            - MONGOPASS=${MONGOPASS}
            - MONGOHOST=${MONGOHOST}
        depends_on:
            - db
    db:
        image: mongo:3.4.2
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGOUSER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
        volumes:
            - "./nginx/dev.nginx.conf:/etc/nginx/nginx.conf"
        depends_on:
            - admin
            - api
            - unity