version: "3"

services:
    admin:
        build:
            context: ./admin
            dockerfile: production.Dockerfile
        environment:
            - MONGODB=${MONGODB}
            - MONGOUSER=${MONGOUSER}
            - MONGOPASS=${MONGOPASS}
            - MONGOHOST=${MONGOHOST}
            - SECRET_KEY=${ADMIN_SECRET_KEY}
            - SECURITY_PASSWORD_SALT=${ADMIN_SECURITY_SALT}
        restart: always
        depends_on:
            - db
    api:
        build:
            context: ./rest
            dockerfile: production.Dockerfile
        volumes:
            - "./admin/app/crud/models.py:/opt/source-code/models.py"
        environment:
            - MONGODB=${MONGODB}
            - MONGOUSER=${MONGOUSER}
            - MONGOPASS=${MONGOPASS}
            - MONGOHOST=${MONGOHOST}
        restart: always
        depends_on:
            - db
    unity:
        build:
            context: ./unity
            dockerfile: Dockerfile
        restart: always
        depends_on:
            - db
    db:
        image: mongo:3.4.2
        volumas:
            - "../edanaga-mongo/:/var/lib/mongodb"
        environment:
            - MONGO_INITDB_ROOT_USERNAME=${MONGOUSER}
            - MONGO_INITDB_ROOT_PASSWORD=${MONGOPASS}
        restart: always

    nginx:
        image: nginx:alpine
        ports:
            - "80:80"
            - "443:443"
        volumes:
            - "./nginx/prod.nginx.conf:/etc/nginx/nginx.conf"
            - "./certbot/conf:/etc/letsencrypt"
            - "./certbot/www:/var/www/certbot"
        environment:
            - THREADS=${NGINXTHREADCOUNT}
        restart: always
        depends_on:
            - admin
            - api
            - unity
    certbot:
        image: certbot/certbot
        volumes:
            - "./certbot/conf:/etc/letsencrypt"
            - "./certbot/www:/var/www/certbot"
        entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
